FROM golang:1.7.5-wheezy

COPY . /go/src/github.com/valuya/docker-volume-curlftpfs
WORKDIR /go/src/github.com/valuya/docker-volume-curlftpfs

RUN set -ex \
    && apt-get install \
        gcc libc-dev \
    && go install --ldflags '-extldflags "-static"'

CMD ["/go/bin/docker-volume-curlftpfs"]